apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: region-health
  name: service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: region-health
  name: config-map-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: region-health
  name: config-map-reader
subjects:
  - kind: ServiceAccount
    name: service-account
    namespace: region-health
roleRef:
    kind: Role
    name: config-map-reader
    apiGroup: rbac.authorization.k8s.io