apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: region-health
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
      - name: frontend-container
        image: phx.ocir.io/axhcuwsuvvsi/region-health/frontend:2163572
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5