apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: oci-health
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  clusterIP: None   # headless — required for StatefulSet DNS
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
