apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api/deployment.yaml
  - api/hpa.yaml
  - api/rbac.yaml
  - api/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml

configMapGenerator:
  - name: postgres-schema
    files:
      - schema.sql=../../app/postgres/schema.sql
    options:
      disableNameSuffixHash: true
